version: '3.8'

services:
  # Trade-Engine Core
  trade-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade-engine-core
    restart: unless-stopped
    # Use host networking for zero network overhead (Linux only)
    # network_mode: "host"  # Uncomment for maximum performance
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./src/trade_engine/core/config:/app/src/trade_engine/core/config:ro
    networks:
      - trade-engine-network
    # Optional: CPU/memory limits for production
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G
    # Uncomment for live trading
    # command: python -m trade_engine.core.engine.runner_live --config /app/src/trade_engine/core/config/live.yaml

  # Trade-Engine API Server (Phase 3)
  # trade-engine-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: trade-engine-api
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOG_LEVEL=INFO
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./logs:/app/logs:ro
  #   networks:
  #     - trade-engine-network
  #   depends_on:
  #     - trade-engine-db
  #   command: uvicorn trade_engine.api.main:app --host 0.0.0.0 --port 8000

  # PostgreSQL Database (Phase 2)
  # trade-engine-db:
  #   image: postgres:16-alpine
  #   container_name: trade-engine-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: trade_engine
  #     POSTGRES_USER: trade_engine_user
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - trade-engine-network
  #   ports:
  #     - "5432:5432"

  # Redis Cache (optional, for API caching)
  # trade-engine-redis:
  #   image: redis:7-alpine
  #   container_name: trade-engine-redis
  #   restart: unless-stopped
  #   networks:
  #     - trade-engine-network
  #   ports:
  #     - "6379:6379"

networks:
  trade-engine-network:
    driver: bridge

volumes:
  postgres-data:
